print("VSCODE WHYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY")
def CHECKIFSAMEBRUH(NUMBAH1,NUMBAH2):
    if(NUMBAH1^NUMBAH2)!= 0:
        print("numbah no equil AHAHQHDVJD<BAJDH<JHDJAKJHDHKGKJHDDA ARGHHHHHHHHHHHHHHHHHHHHHHHH")
    else:
        print("numbah eqil ARGHHHHHHHHHHHHHHHHHHHHHHHH UGH AAAHA AWHHHHHAAHHHHHH")

nom1 = int(input("ente num 1: "))
nom2 = int(input("enta num 2: "))
CHECKIFSAMEBRUH(nom1,nom2)